// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace StudentApp.Models;

[Table("Course")]
public partial class Course
{
    [Key]
    public int Id { get; set; }

    [MaxLength(50)]
    public byte[] Name { get; set; }

    public int? ProgramId { get; set; }

    [ForeignKey("ProgramId")]
    [InverseProperty("Courses")]
    public virtual Programs Program { get; set; }
}