// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace StudentApp.Models;

[Table("Program")]
public partial class Programs
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; }

    public int? Duration { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string ProgramCode { get; set; }

    [InverseProperty("Program")]
    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();
}