// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace StudentApp.Models;

[Table("Student")]
public partial class Student
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string FirstName { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string LastName { get; set; }

    [Column("NRC")]
    public int? Nrc { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Address { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string PhoneNumber { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string StudentId { get; set; }

    public int? ProgramId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateCreated { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastModified { get; set; }

    public int? AttchmentId { get; set; }

    public int? AttatchedFileId { get; set; }

    [ForeignKey("AttatchedFileId")]
    [InverseProperty("Students")]
    public virtual AttachmentFile AttatchedFile { get; set; }

    [ForeignKey("AttchmentId")]
    [InverseProperty("Students")]
    public virtual Attachment Attchment { get; set; }
}