// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace StudentApp.Models;

public partial class StudentManagementContext : DbContext
{
    public StudentManagementContext(DbContextOptions<StudentManagementContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Course> Courses { get; set; }

    public virtual DbSet<Programs> Programs { get; set; }

    public virtual DbSet<Student> Students { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Course>(entity =>
        {
            entity.HasOne(d => d.Program).WithMany(p => p.Courses).HasConstraintName("FK_Course_Program");
        });

        modelBuilder.Entity<Student>(entity =>
        {
            entity.HasOne(d => d.Program).WithMany(p => p.Students).HasConstraintName("FK_Student_Program");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}